server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index viewer.html;

    gzip on;
    gzip_types application/json text/html;
    gzip_min_length 1024;

    location / {
        try_files $uri $uri/ /viewer.html;
    }
}
